spring.application.name=booking
spring.datasource.url=jdbc:postgresql://localhost:5432/serva
spring.datasource.username=postgres
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=validate